nodezoo-metrics:
  build: ../nodezoo-metrics/
  container_name: nodezoo-metrics

nodezoo-github:
  build: ../nodezoo-github/
  container_name: nodezoo-github

nodezoo-info:
  build: ../nodezoo-info/
  container_name: nodezoo-info

nodezoo-npm:
  build: ../nodezoo-npm/
  container_name: nodezoo-npm

nodezoo-search:
  build: ../nodezoo-search/
  container_name: nodezoo-search

nodezoo-web:
  build: ../nodezoo-web/
  container_name: nodezoo-web

concorda-web:
  build: ../concorda-dashboard/
  container_name: concorda-web

vidi-web:
  build: ../vidi-dashboard/
  container_name: vidi-web
