nodezoo_metrics:
  build: ../nodezoo-metrics/
  container_name: nodezoo-metrics

nodezoo_github:
  build: ../nodezoo-github/
  container_name: nodezoo-github

nodezoo_info:
  build: ../nodezoo-info/
  container_name: nodezoo-info

nodezoo_npm:
  build: ../nodezoo-npm/
  container_name: nodezoo-npm

nodezoo_search:
  build: ../nodezoo-search/
  container_name: nodezoo-search

nodezoo_web:
  build: ../nodezoo-web/
  container_name: nodezoo-web

concorda_web:
  build: ../concorda-dashboard/
  container_name: concorda-web

vidi_web:
  build: ../vidi-dashboard/
  container_name: vidi-web
