nodezoo_mesh:
  build: ../node_modules/seneca-mesh-base/
  container_name: nodezoo_mesh

nodezoo_metrics:
  build: ../node_modules/nodezoo-metrics/
  container_name: nodezoo_metrics

nodezoo_info:
  build: ../node_modules/nodezoo-info/
  container_name: nodezoo_info

nodezoo_search:
  build: ../node_modules/nodezoo-search/
  container_name: nodezoo_search

nodezoo_npm:
  build: ../node_modules/nodezoo-npm/
  container_name: nodezoo_npm

nodezoo_github:
  build: ../node_modules/nodezoo-github/
  container_name: nodezoo_github
  environment:
    - TOKEN=67af7d1ffa3bbcbcc13fa417a03c3fc1671ea0f4

nodezoo_travis:
  build: ../node_modules/nodezoo-travis/
  container_name: nodezoo_travis

nodezoo_web:
  build: ../node_modules/nodezoo-web/
  container_name: web
